### ISSUE TITLE
Drupal 10 Support

### ISSUE THREAD

**Issue by trubach** [ATLAS-Illinois/Illinois-Framework-Theme#896]
Drupal 9 support ends in November 2023. This is a parent issue to track what needs to be done for the ILFW to support Drupal 10:

- [x] Add Drupal 10 support to our theme, core module, and profile's .info.yml files
- [x] Update profile composer.json to use core-recommended ^10.0
- [x] #979
- [x] [SimpleSAMLPHP Authentication](https://www.drupal.org/project/simplesamlphp_auth): [Version 4 will support D10](https://www.drupal.org/project/simplesamlphp_auth/issues/3349278)
- [x] Latest SCSS Compiler module release doesn't support D10 - [apply patch and test](https://www.drupal.org/project/scss_compiler/issues/3298001)
- [x] Verify modules and themes included in our distribution support D10
- [x] Upgrade to Drush 12
- [ ] Check CKEditor 5 support
  - [ ] [LinkIt #3232190 - CKEditor 5 readiness](https://www.drupal.org/project/linkit/issues/3232190)
- [ ] [JQuery UI not included in core](https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-or-later/upgrading-from-drupal-9-to-drupal-10-0/migrating-dependencies-on-core-jquery-ui-libraries) - need to check if we need it in the theme or core

Here's an [article that outlines the process of upgrading to Drupal 10](https://gorannikolovski.com/blog/how-to-upgrade-drupal-9-to-10)

**Comment by trubach** [comment]
An article about including custom styles in CKEditor5: https://www.drupal.org/docs/core-modules-and-themes/core-modules/ckeditor-5-module/how-to-style-custom-content-in-ckeditor-5

added stylesheets for ckeditor5, which pulls in the framework type styles, this is different than what people are used to

if you want to make changes to ckeditor5 styles, you need to recompile css
sass --watch scss/ck5style.scss:css/ck5style.css

**Comment by nhjohnstone** [comment]
Info on starterkit theme and creating a custom sub theme: https://www.drupal.org/docs/core-modules-and-themes/core-themes/starterkit-theme

**Comment by trubach** [comment]
RE: SimpleSAMLPHP - here's an alternative authentication method we might use using AzureAD

https://www.drupal.org/docs/contributed-modules/openid-connect-microsoft-azure-ad

**Comment by nhjohnstone** [comment]
No D10 version for SCSS compiler module - patched
https://www.drupal.org/project/scss_compiler/issues/3298001
had to patch the version too

[installed for scss_compiler patch to work](https://github.com/mglaman/composer-drupal-lenient)
composer require mglaman/composer-drupal-lenient

add to composer.json scss patches and drupal-lenient

core modules that are deprecated, uninstall:
[Quick Edit](https://www.drupal.org/node/3223395#s-quick-edit)
[RDF](https://www.drupal.org/docs/core-modules-and-themes/deprecated-and-obsolete-modules-and-themes#s-rdf)

TB megamenu has a version for 9 and a different version for 10, need to include both in composer.json
https://www.drupal.org/project/tb_megamenu - uninstall

theme updates needed: 
 "drupal/bootstrap4": "^3.0", - uninstall
  "drupal/bootstrap5": "^3.0",
 "drupal/tb_megamenu" : "^2.0@alpha||^3.0@alpha" - uninstall

core updates needed:
'drupal/advanced_text_formatter:^3.0@RC'
'drupal/bamboo_twig:^6.0'
'drupal/block_exclude_pages:^2.1@beta'
'drupal/config_sync:^3.0@alpha'
'drupal/pathologic:^2.0@alpha'
'drupal/twig_tweak:^3.2'

"drupal/devel": "^5.1"

test uninstalling these modules before upgrade: 
Blazy, TB megamenu, Bootstrap4, Slick, Slick Views, Video Embed Field, CKeditor(4)
[Google Analytics module is deprecated with GA4](https://www.drupal.org/project/google_analytics) - uninstall?

if you are running into requirements issues
composer prohibits drupal/core 10

had to remove scss_compiler module to run update to d10 and was able to add it back

update 10/11 scss_compiler now has a d10 compatible version, so that has been updated, patches removed

**Comment by nhjohnstone** [comment]
updating to ckeditor5 for basic html text format gives error:
CKEditor 5 only works with HTML-based text formats. The "Video Embed WYSIWYG" (video_embed_wysiwyg) filter implies this text format is not HTML anymore.
https://www.drupal.org/project/video_embed_field/issues/3311063
--10/11 update there is now a patch here we can try to apply
had to disable this, can embed video with media plugin
--11/13 patch applied, the video embed button has been added back to ck editor and seems to be working

other warnings on upgrade to ckeditor5
The CKEditor 4 button Anchor does not have a known upgrade path. If it allowed editing markup, then you can do so now through the Source Editing functionality.
The CKEditor 4 button video_embed does not have a known upgrade path. If it allowed editing markup, then you can do so now through the Source Editing functionality.
The video_embed plugin settings do not have a known upgrade path.
Updating to CKEditor 5 added support for some previously unsupported tags/attributes. A plugin introduced support for the following: These attributes: rowspan (for <th>, <td>), colspan (for <th>, <td>); Additional details are available [in your logs](https://illinois-framework-d10.ddev.site/admin/reports/dblog?type%5B%5D=ckeditor5).

the paste text and paste from word buttons are not in ckeditor 5 
paste with shift added and the word code is stripped out
https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-plain-text.html

in the link tool dialog box, the media library button is no longer there
there is a patch here we are using on extension site:
https://www.drupal.org/project/linkit_media_library/issues/3329877
<img width="50%" alt="Screenshot 2023-11-13 at 9 26 23 AM" src="https://github.com/web-illinois/illinois_framework_theme/assets/97181257/36d73803-9d67-4bed-b523-c16d5ddcc354">
For Extension web site, we might use this module: https://www.drupal.org/project/imce, which opens a file browser instead of the media library. We need to link to PDFs.
<img width="50%" alt="Screenshot 2023-11-10 at 12 26 29 PM" src="https://github.com/web-illinois/illinois_framework_theme/assets/97181257/4de32cef-70df-485e-8e03-bd902b9a217c">

**Comment by nhjohnstone** [comment]
Here is the upgrade status report before updating anything, gives info on what needs to change for ILFW modules
[upgrade-status-export-2023-09-07T20 22 51+0000.txt](https://github.com/web-illinois/illinois_framework_theme/files/12598536/upgrade-status-export-2023-09-07T20.22.51%2B0000.txt)

**Comment by nhjohnstone** [comment]
[Twig tweak updated to 3](https://git.drupalcode.org/project/twig_tweak/-/blob/3.x/docs/migration-to-3.x.md), there are some changes

**Comment by trubach** [comment]
Closing this issue since we've released the ILFW 4.0 with Drupal 10 support. We still need to implement CK Editor 5, but that is in a separate issue.
